### ISSUE TITLE
Error in Jekyll 3.1.6 

### ISSUE THREAD

**Issue by miklb** [omc/searchyll#15]
Assuming the error is in searchyll since I don't get the error with the gem not active.

`jekyll 3.1.6 | Error:  undefined method `[]' for nil:NilClass` 

Not familiar with Ruby enough to know how to dig deeper into the error.

Developing locally with `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]` using homebrew and rbenv

Let me know if I can provide any more details.

**Comment by nz** [comment]
Hey thanks! Could you rerun witih `--trace` and share with us the entire stack trace?

**Comment by miklb** [comment]
Sure thing.
```
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/searchyll-0.9.0/lib/searchyll/configuration.rb:27:in `elasticsearch_index_base_name'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/searchyll-0.9.0/lib/searchyll/indexer.rb:38:in `elasticsearch_index_name'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/searchyll-0.9.0/lib/searchyll/indexer.rb:52:in `prepare_index'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/searchyll-0.9.0/lib/searchyll/indexer.rb:70:in `start'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/searchyll-0.9.0/lib/searchyll.rb:15:in `block in <top (required)>'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/hooks.rb:97:in `block in trigger'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/hooks.rb:96:in `each'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/hooks.rb:96:in `trigger'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/site.rb:166:in `render'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/hooks-9ec9efcbe8e2/lib/octopress-hooks.rb:197:in `render'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/site.rb:59:in `process'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/command.rb:26:in `process_site'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:60:in `build'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:33:in `process'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/commands/serve.rb:34:in `block (2 levels) in init_with_program'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/bin/jekyll:13:in `<top (required)>'
  /usr/local/opt/rbenv/versions/2.3.1/bin/jekyll:23:in `load'
  /usr/local/opt/rbenv/versions/2.3.1/bin/jekyll:23:in `<top (required)>'
```

**Comment by miklb** [comment]
OK, I found the problem, I had some extra spaces in my config file for the searchyll items and I guess it was choking on reading those. Fixing the spacing issues (and subsequently installing a yaml linter) the build succeeds.
File under #notabug
